-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQghNruRzM9/kCEOob1
E5yo0DZM5zhD+7H3jOdYND7OWnSgCgYIKoZIzj0DAQehRANCAAQhv0nXw2dYDdgW
agTrVleoFZFJqHaCYq5T2w7Kh4yXMvdxi9iBbLMeuNNH8XKOIK5j3lrl7gKfakbm
buDqnV0m
-----END PRIVATE KEY-----